# docker-compose.yml
version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    networks:
      - app-tier
    ports:
      - "9092:9092"
      - '9094:9094'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmno1234567
    volumes:
      - kafka_data:/bitnami/kafka

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    networks:
      - app-tier
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: iam_service_db

    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  iam-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - kafka
      - mysql
    ports:
      - "8081:8081"
    networks:
      - app-tier
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/iam_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
volumes:
  kafka_data:
  mysql_data:
networks:
  app-tier:
    driver: bridge