spring.application.name=api-gateway
server.port=${SPRING_BOOT_PORT:${DEFAULT_PORT:8080}}

eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.cloud.gateway.routes[0].id=profile-service
spring.cloud.gateway.routes[0].uri=lb://profile-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/profile/**

spring.cloud.gateway.routes[1].id=iam-authentication
spring.cloud.gateway.routes[1].uri=lb://iam-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/authentication/**
spring.cloud.gateway.routes[1].filters[0]=RemoveRequestHeader=Cookie

spring.cloud.gateway.routes[2].id=iam-service-swagger
spring.cloud.gateway.routes[2].uri=lb://iam-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/iam/**

spring.cloud.gateway.routes[3].id=profile-service-api
spring.cloud.gateway.routes[3].uri=lb://profile-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/profiles/**

spring.cloud.gateway.routes[4].id=iam-users
spring.cloud.gateway.routes[4].uri=lb://iam-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.routes[5].id=iam-users-token
spring.cloud.gateway.routes[5].uri=lb://iam-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/internal/token/inspect
spring.cloud.gateway.routes[6].id=iam-users-roles
spring.cloud.gateway.routes[6].uri=lb://iam-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/roles

springdoc.swagger-ui.enabled=true
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.urls[0].name=IAM-Service
springdoc.swagger-ui.urls[0].url=/iam/v3/api-docs

springdoc.swagger-ui.urls[1].name=Profile-Service
springdoc.swagger-ui.urls[1].url=/profile/v3/api-docs

spring.cloud.gateway.routes[7].id=companies-service
spring.cloud.gateway.routes[7].uri=lb://companies-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/companies/**

spring.cloud.gateway.routes[8].id=companies-swagger
spring.cloud.gateway.routes[8].uri=lb://companies-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/companies/v3/api-docs

spring.cloud.gateway.routes[9].id=paymentcards-service
spring.cloud.gateway.routes[9].uri=lb://paymentcards-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/paymentcards/**

spring.cloud.gateway.routes[10].id=paymentcards-swagger
spring.cloud.gateway.routes[10].uri=lb://paymentcards-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/paymentcards/v3/api-docs

spring.cloud.gateway.routes[11].id=request-service
spring.cloud.gateway.routes[11].uri=lb://request-service
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/v1/requests/**

spring.cloud.gateway.routes[12].id=request-service-swagger
spring.cloud.gateway.routes[12].uri=lb://request-service
spring.cloud.gateway.routes[12].predicates[0]=Path=/request/v3/api-docs

spring.cloud.gateway.routes[13].id=trips-service-swagger
spring.cloud.gateway.routes[13].uri=lb://trip-service
spring.cloud.gateway.routes[13].predicates[0]=Path=/trips/v3/api-docs

springdoc.swagger-ui.urls[2].name=Companies-Service
springdoc.swagger-ui.urls[2].url=/companies/v3/api-docs

springdoc.swagger-ui.urls[3].name=PaymentCards-Service
springdoc.swagger-ui.urls[3].url=/paymentcards/v3/api-docs

springdoc.swagger-ui.urls[4].name=Request-Service
springdoc.swagger-ui.urls[4].url=/request/v3/api-docs
springdoc.swagger-ui.urls[5].name=Trips-Service
springdoc.swagger-ui.urls[5].url=/trips/v3/api-docs
